<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class VendorSeeder extends Seeder
{
    public function run()
    {
        $data = [
            ['vendor_code' => 'V-0001', 'vendor_name' => 'ABI CONDIR SEJAHTERA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0169', 'vendor_name' => 'ABM NISCALA SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0002', 'vendor_name' => 'ACCEL MULTIKIKAI SUKSESTAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0003', 'vendor_name' => 'AGFA SELARAS PRATAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0004', 'vendor_name' => 'AIR LIQUIDE INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0161', 'vendor_name' => 'ALPHA GRAHA COMPUTINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0005', 'vendor_name' => 'ANDI BERKAH KARYA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0006', 'vendor_name' => 'ARKANA MARGAJAYA TEKNINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0166', 'vendor_name' => 'ARTA BUHIN INDUSTRY, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0153', 'vendor_name' => 'ARTAPRIMA SARANA SUKSES, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0007', 'vendor_name' => 'ASERA GEMILANG LESTARI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0008', 'vendor_name' => 'ASIA TALENTA MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0009', 'vendor_name' => 'ASKARA BERKAH ABADI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0178', 'vendor_name' => 'ASPOERNOMO TEKHNIKAL MANDIRI, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0010', 'vendor_name' => 'ATLAS PETROCHEM INDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0179', 'vendor_name' => 'AWIKA SOLUSI', 'is_active' => 1],
            ['vendor_code' => 'V-0011', 'vendor_name' => 'AZ TECS INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0012', 'vendor_name' => 'BERCA MANDIRI PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0013', 'vendor_name' => 'BORNEO STATIONERY', 'is_active' => 1],
            ['vendor_code' => 'V-0014', 'vendor_name' => 'BUANA ABADI MASINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0199', 'vendor_name' => 'BUANA INDOMOBIL TRADA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0174', 'vendor_name' => 'BUANA INDOMOBIL TRADA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0015', 'vendor_name' => 'BUHLER INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0016', 'vendor_name' => 'CGS INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0017', 'vendor_name' => 'CHAMPION PRECISION PARTS INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0018', 'vendor_name' => 'CIPTAMITRA BINA LESTARI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0019', 'vendor_name' => 'COSMOWAVE, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0189', 'vendor_name' => 'CYGNUS CYRUS CEMERLANG, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0020', 'vendor_name' => 'DAIKI ALUMINIUM INDUSTRY INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0162', 'vendor_name' => 'DAISY JAYA TECHNOLOGY, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0021', 'vendor_name' => 'DANEL SUKSES MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0022', 'vendor_name' => 'DARUMA ADIRA PRATAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0023', 'vendor_name' => 'DSL INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0024', 'vendor_name' => 'DUTA MULYA JAYA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0170', 'vendor_name' => 'DWI MANUNGGAL SUKSES ENGINEERING, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0025', 'vendor_name' => 'DYAS MARTO PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0026', 'vendor_name' => 'ELECTRA JAYA SEMESTA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0027', 'vendor_name' => 'ELECTRINDO TEHNIKA PRIMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0028', 'vendor_name' => 'ELO DUNIA MITRASARANA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0029', 'vendor_name' => 'FARCO ENERGI INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0030', 'vendor_name' => 'FASH ON KARYA GEMILANG', 'is_active' => 1],
            ['vendor_code' => 'V-0031', 'vendor_name' => 'FEDERAL GRAND INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0032', 'vendor_name' => 'FLEKSI AUTO SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0033', 'vendor_name' => 'FORTA LARESE, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0034', 'vendor_name' => 'FOSECO INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0168', 'vendor_name' => 'FUMIYUKI GLOBAL SOLUSINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0035', 'vendor_name' => 'GEMA OMNI FORTUNA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0036', 'vendor_name' => 'GEMILANG PRIORITAS UTAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0037', 'vendor_name' => 'GIGA CREATIVE ENGINEERING, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0038', 'vendor_name' => 'GLOBAL BITUMEN UTAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0039', 'vendor_name' => 'GLOBAL MANDIRI INSTRUMENTASI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0040', 'vendor_name' => 'GUNUNG MUTIARA NEDINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0041', 'vendor_name' => 'HARMONY GEMILANG SUKSES, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0154', 'vendor_name' => 'HASTA MANDIRI SEPAKAT, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0042', 'vendor_name' => 'HATEK ANUGRAH CEMERLANG, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0043', 'vendor_name' => 'HEXAGRAPHIA', 'is_active' => 1],
            ['vendor_code' => 'V-0044', 'vendor_name' => 'HIDEKI TRAKTOR INDONESIA ,PT', 'is_active' => 1],
            ['vendor_code' => 'V-0045', 'vendor_name' => 'HITEC MITRA SELARAS, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0046', 'vendor_name' => 'HONDA TRADING INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0047', 'vendor_name' => 'HYDROKARYA UTAMA', 'is_active' => 1],
            ['vendor_code' => 'V-0048', 'vendor_name' => 'INDONESIA EPSON INDUSTRY, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0049', 'vendor_name' => 'INDRAGRAHA NUSAPLASINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0050', 'vendor_name' => 'INFINYS SYSTEM INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0149', 'vendor_name' => 'INTEC INSTRUMENTS, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0152', 'vendor_name' => 'INTERIOR DELAPAN DELAPAN', 'is_active' => 1],
            ['vendor_code' => 'V-0051', 'vendor_name' => 'INTERNASIONAL TEKNIK SOLUSINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0052', 'vendor_name' => 'INTI SUPPLIES MEGA PERKASA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0053', 'vendor_name' => 'INTI SURYA LABORATORIUM, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0054', 'vendor_name' => 'INTI WARNA CEMERLANG, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0055', 'vendor_name' => 'ISK INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0056', 'vendor_name' => 'JAKARTA MAJU AGUNG PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0057', 'vendor_name' => 'JAVA TRITECH INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0058', 'vendor_name' => 'JAYA MEKATRONIKA INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0059', 'vendor_name' => 'JAYA METAL TEKNIKA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0060', 'vendor_name' => 'JAYAINDO ABADI MAKMUR, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0061', 'vendor_name' => 'JINGGA JAYA ABADI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0062', 'vendor_name' => 'JINGGA METROLOGI SOLUSI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0063', 'vendor_name' => 'JUBASSEN ABDI SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0064', 'vendor_name' => 'KALINGGA TATARAYA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0065', 'vendor_name' => 'KANAKA NIRBANA INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0066', 'vendor_name' => 'KARYA JAYA LOGAMINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0067', 'vendor_name' => 'KARYA SUKSES STEEL, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0068', 'vendor_name' => 'KASANA TEKNINDO GEMILANG, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0069', 'vendor_name' => 'KAWAN LAMA SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0150', 'vendor_name' => 'KAWAN LAMA SOLUSI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0185', 'vendor_name' => 'KAYABA INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0159', 'vendor_name' => 'KEDUNG RAJAKI ADHINATA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0172', 'vendor_name' => 'KIMIA YASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0070', 'vendor_name' => 'KREASI DASATAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0071', 'vendor_name' => 'KREXINDO MANUNGGAL PUTRA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0164', 'vendor_name' => 'KROMO SAKTI MANDRAGUNA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0072', 'vendor_name' => 'LIANG CHI INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0073', 'vendor_name' => 'LINDE INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0074', 'vendor_name' => 'MAHA DAYA ENERGI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0075', 'vendor_name' => 'MAHA MERU TEKNIK, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0076', 'vendor_name' => 'MAKMUR META GRAHA DINAMIKA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0151', 'vendor_name' => 'MALZIRA MAJU SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0077', 'vendor_name' => 'MANDIRI ADHI SENTOSA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0177', 'vendor_name' => 'MANDIRI ANUGERAH S, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0155', 'vendor_name' => 'MANDIRI TRANSFORMA GLOBAL, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0078', 'vendor_name' => 'MARRA MULTI SUKSES, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0079', 'vendor_name' => 'MAYOMA INTRA GEMILANG, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0173', 'vendor_name' => 'MEGA KITCHEN SET', 'is_active' => 1],
            ['vendor_code' => 'V-0080', 'vendor_name' => 'MEGATAMA SPRING, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0191', 'vendor_name' => 'MEIWA MOLD INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0167', 'vendor_name' => 'METROPOLITAN MITRA UTAMA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0184', 'vendor_name' => 'MITRA CIPTA TEKNIKA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0194', 'vendor_name' => 'MITRA ELEKTRONIK SOLUSINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0081', 'vendor_name' => 'MITRA TEKNIK SEJAHTERA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0198', 'vendor_name' => 'MITRA UTAMA LESTARI ABADI', 'is_active' => 1],
            ['vendor_code' => 'V-0082', 'vendor_name' => 'MITRAMETAL PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0083', 'vendor_name' => 'MITUTOYO INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0084', 'vendor_name' => 'MORESCO INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0171', 'vendor_name' => 'MUJURA SAKTI ABADI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0180', 'vendor_name' => 'MULAN KENCANA GROUP, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0190', 'vendor_name' => 'MULTI INDO TEKNIK, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0085', 'vendor_name' => 'MULTI SARANA SAKTI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0086', 'vendor_name' => 'MULTIPLE VARINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0196', 'vendor_name' => 'MULTITEKNO ANALITIKA INDONUSA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0087', 'vendor_name' => 'NANDYA KARYA PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0145', 'vendor_name' => 'NETMARKS INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0088', 'vendor_name' => 'NIHON SEIKI INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0188', 'vendor_name' => 'NIHONA PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0187', 'vendor_name' => 'NIKITOOLS REKAYASA MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0165', 'vendor_name' => 'NR ABADI SUKSES, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0089', 'vendor_name' => 'OSIDIA SERVICE INDUSTRY, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0090', 'vendor_name' => 'OTOZONE', 'is_active' => 1],
            ['vendor_code' => 'V-0091', 'vendor_name' => 'PANANJUNG ANUGRAH SOLUTION, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0092', 'vendor_name' => 'PANCA INTI NUSANTARA SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0093', 'vendor_name' => 'PANDULIMA HYDROMATIC, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0094', 'vendor_name' => 'PASS CHELCO INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0095', 'vendor_name' => 'PERKASA ALEEN TEKNIK, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0157', 'vendor_name' => 'PILAR LOGAM PERKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0096', 'vendor_name' => 'PINJAYA ABADI METAL, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0097', 'vendor_name' => 'PLASTINDO KAWAN SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0098', 'vendor_name' => 'PRAMA MULTI PRAKASA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0163', 'vendor_name' => 'PRAMATEK ANDAL ANALITIKA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0099', 'vendor_name' => 'PRIMA GUNA HATTA ASRI, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0100', 'vendor_name' => 'PROPACK KREASI MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0160', 'vendor_name' => 'PT. GRATIA MULTI SEJAHTERA', 'is_active' => 1],
            ['vendor_code' => 'V-0176', 'vendor_name' => 'PT. JIMA TARA', 'is_active' => 1],
            ['vendor_code' => 'V-0193', 'vendor_name' => 'PT. OERLIKON BALZERS ARTODA INDONESIA', 'is_active' => 1],
            ['vendor_code' => 'V-0101', 'vendor_name' => 'PUJI LESTARI PURNAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0102', 'vendor_name' => 'RADIKA MITRA JAYA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0103', 'vendor_name' => 'RAFITAMA MILLENIAL WAHYUDI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0104', 'vendor_name' => 'RAMBU TEKNINDO MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0197', 'vendor_name' => 'RINDANG ROMA NAULI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0105', 'vendor_name' => 'SAFIRA NUSANTARA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0106', 'vendor_name' => 'SAIKI PUTRA TEKNINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0107', 'vendor_name' => 'SANDIMAN TEHNIK, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0108', 'vendor_name' => 'SANDY GLOBALINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0109', 'vendor_name' => 'SANENG INDUSTRIAL, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0110', 'vendor_name' => 'SANOH INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0182', 'vendor_name' => 'SELEKTA KENCANA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0111', 'vendor_name' => 'SEMAR GEMILANG, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0147', 'vendor_name' => 'SENTOSA METALURGI INDOMAS, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0112', 'vendor_name' => 'SGS INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0113', 'vendor_name' => 'SHADANA PERSADA GEMILANG, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0114', 'vendor_name' => 'SHERICH INTERNATIONAL SUPPLY, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0115', 'vendor_name' => 'SHIBAURA MACHINE INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0186', 'vendor_name' => 'SINAR BAHAGIA GAJAHMADA', 'is_active' => 1],
            ['vendor_code' => 'V-0116', 'vendor_name' => 'SINAR MUTIARA CAKRABUANA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0117', 'vendor_name' => 'SINAR MUTIARA EPC, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0118', 'vendor_name' => 'SINAR PELITA SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0119', 'vendor_name' => 'SINAR PROTEKSINDO OPTIMAL, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0120', 'vendor_name' => 'SINAR SUBUR LOGAMINDO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0121', 'vendor_name' => 'SINERGI ENGINEERING SEJAHTERA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0148', 'vendor_name' => 'SINERGI SEMESTA PRATAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0122', 'vendor_name' => 'SMART MITRA SOLUTION, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0123', 'vendor_name' => 'SOMAGEDE INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0146', 'vendor_name' => 'SS BERSAUDARA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0124', 'vendor_name' => 'SUKANDA DJAYA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0183', 'vendor_name' => 'SUMBERTAMA JAYA TEKNIK, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0181', 'vendor_name' => 'SUMI WIN MUKTI', 'is_active' => 1],
            ['vendor_code' => 'V.00000', 'vendor_name' => 'Supplier Umum', 'is_active' => 1],
            ['vendor_code' => 'V-0125', 'vendor_name' => 'TEKNOLOGI MITRA SERASAN, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0192', 'vendor_name' => 'TESLA TEKNOLOGI INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0126', 'vendor_name' => 'THREEBOND GARPAN SALES INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0127', 'vendor_name' => 'TITAN TEKNIKATAMA INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0156', 'vendor_name' => 'TOGU RAYA KREASI MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0128', 'vendor_name' => 'TOMIDA GLOSSINDO INDAH, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0129', 'vendor_name' => 'TRI TUNGGAL FONDASI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0158', 'vendor_name' => 'TRIEKSIS INDONESIA', 'is_active' => 1],
            ['vendor_code' => 'V-0130', 'vendor_name' => 'TRIMITRA INTIGRAHA PRATAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0131', 'vendor_name' => 'TRITECH MITRA PERSADA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0132', 'vendor_name' => 'TUNAS JAYA ARYATAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0133', 'vendor_name' => 'USAHA JAYA', 'is_active' => 1],
            ['vendor_code' => 'V-0134', 'vendor_name' => 'USAHA SAUDARA MANDIRI, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0175', 'vendor_name' => 'UTILINDO ANAYA, CV', 'is_active' => 1],
            ['vendor_code' => 'V-0135', 'vendor_name' => 'VALGRE INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0136', 'vendor_name' => 'VIRA INTERCO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0195', 'vendor_name' => 'VIVA MEDIKA', 'is_active' => 1],
            ['vendor_code' => 'V-0137', 'vendor_name' => 'WILISINDOMAS INDAHMAKMUR, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0138', 'vendor_name' => 'YAKSA GAMA NUSWANTORO, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0139', 'vendor_name' => 'YAMAZEN INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0140', 'vendor_name' => 'YAN PURNAMA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0141', 'vendor_name' => 'YOGYA PRESISI TEHNIKATAMA INDUSTRY, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0142', 'vendor_name' => 'YOISA MITRA INDONESIA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0143', 'vendor_name' => 'YOSRAN INTAN PERMATA, PT', 'is_active' => 1],
            ['vendor_code' => 'V-0144', 'vendor_name' => 'ZOLATECH PERDANA, PT', 'is_active' => 1],
        ];

        // Insert batch per chunk biar aman & cepat
        $table = $this->db->table('vendors');

        // kalau vendor_code UNIQUE, ini akan skip yang sudah ada (MySQL/MariaDB)
        $chunkSize = 300;
        foreach (array_chunk($data, $chunkSize) as $chunk) {
            $table->ignore(true)->insertBatch($chunk);
        }
    }
}
